version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres:5432/postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: npm run start:dev products
    env_file:
      - ./apps/products/.env
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres:5432/postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      PORT: 3000
    ports:
      - '3000:3000'
  suppliers:
    build:
      context: .
      dockerfile: ./apps/suppliers/Dockerfile
      target: development
    command: npm run start:dev suppliers
    env_file:
      - ./apps/suppliers/.env
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres:5432/postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      PORT: 4000
    ports:
      - '4000:4000'
