###################### Products ####################
### Create a new product
POST  http://localhost:3000/products
content-type: application/json

{
    "name":" product 4",
    "stock":10,
    "measurement": {
        "name": "killo",
        "symbol": "k",
        "id": 1
    },
    "category":{
        "id":1,
        "name":"vegetables"
    },
    "supplierProducts":[{
        "supplier_id":1,
        "price":20
    }]
}

### Get all products
GET http://localhost:3000/products

### Update the stock of a product
PATCH   http://localhost:3000/products/2/stock
content-type: application/json

{
    "stockNumber":7
}

###################### Meaurements ####################
### Create a new measurement
POST  http://localhost:3000/measurements
content-type: application/json

{
    "name":"gram",
    "symbol":"g"
}


###################### categories ####################
### Create a new category
POST  http://localhost:3000/categories
content-type: application/json

{
    "name":"vegetables"
}


###################### suppliers ####################
### Create a new supplier
POST  http://localhost:4000/suppliers
content-type: application/json

{
    "name":"third supplier"
}


### Get all suppliers
GET http://localhost:4000/suppliers




